### ISSUE TITLE
Pattern matcher fails when specifying unidirectional sync

### ISSUE THREAD

**Issue by jgigliotti** [jacobwgillespie/plex-sync#14]
Example:
`$ DRY_RUN=1 plex-sync 192.168.55.51/2,r 192.168.55.247,w`

Pattern matcher seem so to come up matchless when the last server in the list has a a single 'r' or single 'w' ('rw' works okay).

**Comment by jgigliotti** [comment]
Regex isn't my strong suit, but #15 seems to do the trick

**Comment by jacobwgillespie** [comment]
Closed in #15
