### ISSUE TITLE
Seems to fail to sync status of "unavailable" media

### ISSUE THREAD

**Issue by feld** [jacobwgillespie/plex-sync#17]
Not sure if this is a Plex API limitation or something happening in the code here. Haven't identified anything obvious though.

Eg, I archived a show off my server to an external drive and it is currently unavailable. It is available on another server of mine. The sync does not marked episodes as watched on the server where the show is available. This is very disappointing.

**Comment by jacobwgillespie** [comment]
So, you watched the show on one server, then archived it, and now it won't sync as watched to another server?

Makes sense.  I don't know why it would be like that, but I can try to debug.  Are you able to grab the contents of the following link and post them here or email them to me at jacobwgillespie@gmail.com?

```
http://SERVER_HOST/library/sections/SECTION_NUMBER/allLeaves?X-Plex-Token=PLEX_TOKEN
```

Ideally if you can do that for both servers / library numbers, that would be awesome.  If not, we can try to narrow down what it's returning in there for each show.

**Comment by jacobwgillespie** [comment]
Any chance to take a look at this?

**Comment by jacobwgillespie** [comment]
I believe this is a limitation of the Plex API, but if you do get a copy of those sample XML responses, I'd be happy to take a look to see if there's a workaround.  I'm going to close this for now, but feel free to post back if anything changes.
