### ISSUE TITLE
Does it Support Multiple Users?

### ISSUE THREAD

**Issue by kenrick** [jacobwgillespie/plex-sync#24]
Hey there! I wanted to know if this library will sync the watch statuses of multiple users.

- Thanks

**Comment by jacobwgillespie** [comment]
It does, yep!  You would use different access tokens to specify the different users.

So, if your server IP was `10.0.0.10` and the library section ID was `1`, then you'd capture the tokens `xxxxxxxx` and `yyyyyyyy` from the different users and run the command like so:

```shell
$ plex-sync xxxxxxxx@10.0.0.10/1 yyyyyyyy@10.0.0.10/1
```

Make sense?

**Comment by kenrick** [comment]
Yeah I understood that part. My problem is getting the tokens of other users. Can you point me the right direction?

These are users are shared my plex account with btw.

**Comment by jacobwgillespie** [comment]
I made a bookmarklet here that you can use: https://jacobwgillespie.github.io/plex-token-bookmarklet/.

You essentially have to log in as each user and use the bookmarklet or other means to acquire the token.  As far as I know, there's no way to get tokens for other users without just logging in as them.

So, you'd either have to log in as each user you want to sync to capture the token, or have each of your users send you their tokens.

**Comment by kenrick** [comment]
Thanks
