### ISSUE TITLE
Getting TypeError when trying to sync other users

### ISSUE THREAD

**Issue by MearWolf** [jacobwgillespie/plex-sync#28]
TypeError: Cannot read property 'Video' of undefined
    at /usr/local/lib/node_modules/plex-sync/lib/plex.js:78:40
    at process._tickCallback (node.js:368:9)

**Comment by johnypony3** [comment]
I'm getting a similar error running this command:
`plex-sync token@server1/port1 token@server2/port2`

Error:
> Reading data from server1:port1, server2:port2...
> Progress:                      | Elapsed: 0.0s | 100%
> TypeError: Cannot read property 'Video' of undefined
>     at /usr/local/lib/node_modules/plex-sync/lib/plex.js:78:40
>     at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by stian89** [comment]
Sam here. Seems like the Plex home users are not authorized to change the watch status as it is now.. Hope someone finds an answer. :)

**Comment by jacobwgillespie** [comment]
As best as I can tell, some of you are experiencing issues with the requests timing out for larger libraries - I just released `v0.6.0` which now fetches items from the library 32 at a time, the same as the Plex web client, which should alleviate that issue.

I am able to sync across Plex Home users, but I suspect there's some difference between my setup and @stian89's setup.  I'll reply on that issue at #27.

Let me know if `v0.6.0` resolves the issue.

**Comment by jacobwgillespie** [comment]
I'm going to close this issue for now, but feel free to post back if `v0.6.0` doesn't resolve the issue.
