### ISSUE TITLE
feature request: uni-directional sync

### ISSUE THREAD

**Issue by MearWolf** [jacobwgillespie/plex-sync#5]
This software is brilliant, the solution I've been looking for, for quite a while.

Though is one feature I'd like:
I'd like to be able to merely mirror my viewstate from server01 to servers02 and following...

**Comment by jacobwgillespie** [comment]
This is a good suggestion - should be pretty easy to implement.

**Comment by jacobwgillespie** [comment]
Just released v0.3.0 which implements this.  The server arguments optionally have a mode string `,rw` which specifies whether to read from or write to a particular library.  I would recommend testing it to be sure it works as intended, however you shouldbe able to do something like the following:

```shell
$ plex-sync server01/1,r server02/1,w server03/1,w
```
