### ISSUE TITLE
Running Multiple Syncs In Batch File - Only Runs First

### ISSUE THREAD

**Issue by Migz93** [jacobwgillespie/plex-sync#63]
I have a batch file with all my different plex-sync commands, so a total of 24 lines with each one syncing either a different user or a different library for a user.

But whenever i run the batch file it only seems to run the first line and then once that sync completes it just exits.

I then tried making a master batch file which would call 24 individual batch files, each one having a single command in it followed by "exit" on the next line so that i don't end up with loads of commad prompt windows open but doing it this way it still seems to just stop after the plex-sync line and never exits.

Am i doing something stupid or?

**Comment by Kazz3r24** [comment]
I'd have to see your script to know for sure, not enough info to go by here. I assume that you're running on Windows? 

The following link isn't completely related, but it does discuss continuing a .bat file after a command is run, which is what you're looking for.
[https://stackoverflow.com/questions/6354240/have-bat-file-continue-after-it-runs-a-command](url)

I personally use Linux, which is easy enough to continue a script after successful command completion.

**Comment by robdplatt** [comment]
I had the same problem. My batch files are setup this way

```
@echo off
echo Syncing Movies
cmd /c plex-sync token@ip/1 token@ip2/1
echo Syncing TV
cmd /c plex-sync token@ip/2 token@ip2/2
```

I'm using nodejs-portable.
