### ISSUE TITLE
Bidirectional sync?

### ISSUE THREAD

**Issue by segator** [jacobwgillespie/plex-sync#72]
user A connect to server A and watch a movie

next day user A connect to server B and he can see the movie seen yesterday marked as watched, he now watch an other movie on Server B.

I expect (after sync) the movie watched on server B is marked on server A.

That's correct? that's mean the sync is bidirectional?

**Comment by jacobwgillespie** [comment]
You are correct, bidirectional sync is the default behavior

**Comment by segator** [comment]
Thank you!
